server {
    listen 80 default_server;
    root /var/www/skymedia/public;
    index index.php;

    access_log /dev/stdout;
    error_log  /dev/stderr;

    client_max_body_size 512M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass  unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include       fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\. { deny all; }
    location /storage/dvr/ { deny all; }
}
